hadoop:
  image: izone/hadoop:mahout
  container_name: Mahout
  hostname: hadoop
  ports:
  - 8888:8888
  - 8088:8088
  - 8042:8042
  - 50070:50070
  - 4040:4040
  - 8080:8080
  links:
  - mariadb:mariadb
#  - oraclexe:oraclexe
#  - mongodb:mongodb
  volumes:
  - $HOME/notebooks:/root/notebooks
mariadb:
  image: mariadb:10.1.19
  container_name: MariaDB
  hostname: mariadb
  ports:
  - 3306:3306
  environment:
  #MYSQL_ALLOW_EMPTY_PASSWORD=yes
  - MYSQL_ROOT_PASSWORD=maria
oraclexe:
  image: izone/oracle:11g
  container_name: OracleXE
  hostname: oraclexe
  ports:
  - 1521:1521
mongodb:
  image: izone/mongodb
  container_name: MongoDB
  hostname: mongodb
  ports:
  - 27017:27017
  - 28017:28017
  environment:
  - AUTH=no
  #MONGODB_PASS="mongo"
  volumes:
  - $HOME/mongodb/data/db:/data/db


